# Generated by Django 5.2.8 on 2025-11-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Make Your Event Unforgettable', max_length=200)),
                ('subtitle', models.TextField(default='Plan the perfect day with our expert event management services.')),
                ('button_text', models.CharField(default='Book Your Event', max_length=50)),
                ('button_url', models.URLField(default='#')),
                ('background_image', models.ImageField(upload_to='hero_banners/')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
            },
        ),
    ]
