# Generated by Django 5.2.8 on 2025-11-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(default='unknown', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='venue',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
