# Generated by Django 5.2.8 on 2025-11-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_booking_customer_name_booking_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='venue',
            field=models.TextField(),
        ),
    ]
