# Generated by Django 5.2.8 on 2025-11-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_booking_amount_paid_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
